In [ ]:
#Data Encoding 
#Model only understands numerical data so we have to convert categorial data to numerical data we do this by data encoding

In [1]:
#1. Nominal/One Hot Encoding (OHE)
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder

In [5]:
##Creating a simple DF
df = pd.DataFrame({
    'color': ['red','blue','green','green','red']
})

In [6]:
df

   color
0    red
1   blue
2  green
3  green
4    red

In [7]:
## Creating instance of One hot Encoder
encoder=OneHotEncoder()

In [ ]:
## Perform Fit (learn about all the categories) and Transform (convert the learned information to data 0,1)
#  either use fit() and transform() seperately or in one line
encoded=encoder.fit_transform(df[['color']]).toarray()# does alphabet sorting starts with Blue then Green then Red

In [25]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [11]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0

In [ ]:
## For new data to check 
encoder.transform([['blue'],['red']]).toarray()

C:\Users\ayush\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

ValueError: Found unknown categories ['blue'] in column 0 during transform

In [15]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0

In [19]:
#Dataset Tips
import seaborn as sns
df=sns.load_dataset('tips')

In [24]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
encoder=OneHotEncoder()

In [35]:
encoded=encoder.fit_transform(df[['sex','smoker','day','time']]).toarray()

In [36]:
encoded

array([[1., 0., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       [1., 0., 1., ..., 1., 1., 0.]], shape=(244, 10))

In [40]:
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [54]:
encoder_df

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
243,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [58]:
new_pd=pd.concat([df,encoder_df],axis=1)

In [59]:
new_pd.drop(columns=['total_bill','tip','size'])

,sex,smoker,day,time,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,Female,No,Sun,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,Male,No,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,Male,No,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,Male,No,Sun,Dinner,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,Female,No,Sun,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,Male,No,Sat,Dinner,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,Female,Yes,Sat,Dinner,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,Male,Yes,Sat,Dinner,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,Male,No,Sat,Dinner,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
243,Female,No,Thur,Dinner,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0