In [1]:
##4.Target Guided Oridnal Encoding
# Technique used to encode cat variables based on their relationship with the target variable

In [1]:
import pandas as pd 

df= pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200,150,300,250,180,320]#assume this is target variable
})

In [2]:
df

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    180
5     Paris    320

In [3]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [4]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [5]:
df['city_encoded']=df['city'].map(mean_price)

In [6]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         310.0

In [7]:
df[['city_encoded','price']]

   city_encoded  price
0         190.0    200
1         150.0    150
2         310.0    300
3         250.0    250
4         190.0    180
5         310.0    320

In [17]:
df_label=df.groupby('city')['price'].mean().sort_values().index
df_mapping={k:i for i,k in enumerate(df_label)}

In [18]:
df_mapping

{'London': 0, 'New York': 1, 'Tokyo': 2, 'Paris': 3}

In [19]:
df['updated']=df['city'].map(df_mapping)

In [22]:
df[['city','updated','price']]

       city  updated  price
0  New York        1    200
1    London        0    150
2     Paris        3    300
3     Tokyo        2    250
4  New York        1    180
5     Paris        3    320

In [34]:
#Time based on total_bill target 
import seaborn as sns
df = sns.load_dataset('tips')

In [35]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [51]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [50]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

C:\Users\ayush\AppData\Local\Temp\ipykernel_4548\478333798.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [61]:
mean_price=df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\ayush\AppData\Local\Temp\ipykernel_4548\478333798.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price=df.groupby('time')['total_bill'].mean().to_dict()

In [62]:
mean_price

{'Lunch': 17.168676470588235, 'Dinner': 20.79715909090909}

In [64]:
df['time_encoded']=df['time'].map(mean_price)

In [ ]:
df[['time','time_encoded','total_bill']]

       time time_encoded  total_bill
0    Dinner    20.797159       16.99
1    Dinner    20.797159       10.34
2    Dinner    20.797159       21.01
3    Dinner    20.797159       23.68
4    Dinner    20.797159       24.59
..      ...          ...         ...
239  Dinner    20.797159       29.03
240  Dinner    20.797159       27.18
241  Dinner    20.797159       22.67
242  Dinner    20.797159       17.82
243  Dinner    20.797159       18.78

[244 rows x 3 columns]

In [96]:
label=df.groupby('time')['total_bill'].mean().sort_values().index
df_mapping={k:i for i,k in enumerate(label)}

C:\Users\ayush\AppData\Local\Temp\ipykernel_4548\2549048143.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  label=df.groupby('time')['total_bill'].mean().sort_values().index

In [97]:
df_mapping

{'Lunch': 0, 'Dinner': 1}

In [98]:
df['updated']=df['time'].map(df_mapping)

In [99]:
label

CategoricalIndex(['Lunch', 'Dinner'], categories=['Lunch', 'Dinner'], ordered=False, dtype='category', name='time')

In [100]:
df[['time','updated','time_encoded','total_bill']]

       time updated time_encoded  total_bill
0    Dinner       1    20.797159       16.99
1    Dinner       1    20.797159       10.34
2    Dinner       1    20.797159       21.01
3    Dinner       1    20.797159       23.68
4    Dinner       1    20.797159       24.59
..      ...     ...          ...         ...
239  Dinner       1    20.797159       29.03
240  Dinner       1    20.797159       27.18
241  Dinner       1    20.797159       22.67
242  Dinner       1    20.797159       17.82
243  Dinner       1    20.797159       18.78

[244 rows x 4 columns]